In [2]:
import numpy as np
import math

k = 1 /math.sqrt(2)
print("matriisi M")
M = np.array([[0,0,k,k], [k,-k,0,0], [k, k, 0,0], [0,0,k,-k]])
print(M)

print("kantavektori")
q00 =np.array([[1],[0],[0],[0]])
print(q00)

print("lasketaan matriisin M ja kantavektorin tulo")
print(M@q00)

print("onko unitaarinen")
print(M@M)

X = np.array([[0,1], [1,0]])
print(X)

print("Not portti on unitarinen: xx=I")
print(X@X)

print("lasketaan M:n ja Bellin tilan tulo")
print(M@M@q00)

matriisi M
[[ 0.          0.          0.70710678  0.70710678]
 [ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678 -0.70710678]]
kantavektori
[[1]
 [0]
 [0]
 [0]]
lasketaan matriisin M ja kantavektorin tulo
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]
onko unitaarinen
[[ 0.5  0.5  0.5 -0.5]
 [-0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5  0.5]
 [ 0.5  0.5 -0.5  0.5]]
[[0 1]
 [1 0]]
Not portti on unitarinen: xx=I
[[1 0]
 [0 1]]
lasketaan M:n ja Bellin tilan tulo
[[ 0.5]
 [-0.5]
 [ 0.5]
 [ 0.5]]
