In [7]:
import numpy as np
import math

k = 1 /math.sqrt(2)
print("matriisi M")
M = np.array([[0,0,k,k], [k,-k,0,0], [k, k, 0,0], [0,0,k,-k]])
print(M)

print("kantavektori")
q00 =np.array([[1],[0],[0],[0]])
print(q00)

print("lasketaan matriisin M ja kantavektorin tulo")
print(M@q00)

print("Muodostetaan Matriisin M käänteismatriisi laskemalla M:n transpoosin kompleksikonjukaatti:")
M_inv = M.transpose()
print(M_inv)
print("Onko M unitaarinen, lasketaan M:n ja sen kompleksikonjukaatin transpoosin tulo")
print(M@M_inv)
print("M on siis unitaarinen, koska M*M_inv = I identiteettimatriisi")

X = np.array([[0,1], [1,0]])
print(X)


print("Not-portti X on myös unitarinen: xx=I")
print(X@X)


print("Bellin tila: Matriisi M muuntaa vektorin |00> Bellin tilaksi ")
Bell_state = M@q00
print(Bell_state)

print("lasketaan M_inv:n ja Bellin tilan tulo: M_inv muuntaa Bellin tilan takaisin kantavektoriksi |00>")
print(M_inv@Bell_state)

matriisi M
[[ 0.          0.          0.70710678  0.70710678]
 [ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678 -0.70710678]]
kantavektori
[[1]
 [0]
 [0]
 [0]]
lasketaan matriisin M ja kantavektorin tulo
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]
Muodostetaan Matriisin M käänteismatriisi laskemalla M:n transpoosin kompleksikonjukaatti:
[[ 0.          0.70710678  0.70710678  0.        ]
 [ 0.         -0.70710678  0.70710678  0.        ]
 [ 0.70710678  0.          0.          0.70710678]
 [ 0.70710678  0.          0.         -0.70710678]]
Onko M unitaarinen, lasketaan M:n ja sen kompleksikonjukaatin transpoosin tulo
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -2.23711432e-17]
 [ 0.00000000e+00  1.00000000e+00 -2.23711432e-17  0.00000000e+00]
 [ 0.00000000e+00 -2.23711432e-17  1.00000000e+00  0.00000000e+00]
 [-2.23711432e-17  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
M on 